### ISSUE TITLE
Radarsat2 collection beam mode/ beam mnemonic / product type

### ISSUE THREAD

**Issue by ECCCBen** [m9brady/eodms-api-client#2]
Tried to query eodms api for R2 dataset and limit query to SGF (-pt), SCWA (-bm) with no success. Could be an issue with EODMS itself since I sometimes have similar issues when querying EODMS for their online portal...

eodms -c Radarsat2 -s 20180205 -e 20181231 -pt SGF -g CG_EODMS_Query.geojson -dr

[eodms-api-client-debug.zip](https://github.com/m9brady/eodms-api-client/files/6576578/eodms-api-client-debug.zip)

**Comment by m9brady** [comment]
Can confirm - `beam_mode` filter doesn't appear to do anything to the result of a query. Even the official client appears to not use the `.SBEAM` filter: https://github.com/nrcan-eodms-sgdot-rncan/eodms-rapi-orderdownload/blob/1b633f61815a7a7d3e5514f7ead617335fb695c8/utils/common.py#L93

In the meantime, you can use some geopandas magic to get rid of anything that isn't SCWA before ordering:
```python
import geopandas as gpd
df = gpd.read_file('query_results.geojson')
scwa_only = df.loc[df['Position'] == 'SCWA']
with open('to_order.txt', 'w') as f:
    f.writelines('\n'.join(scwa_only['EODMS RecordId'].astype(str).tolist()))
```

**note that there may be some "duplicate" scenes (same image but different LUT) so be sure to order only what you want**

then submit:
```shell
eodms -c RS2 --record-ids to_order.txt
```

**Comment by m9brady** [comment]
@NWRCBen FYI as of 4f2730195e6ea3e2c18cb794b372182fbd173f2f (not released/published to pypi/cforge yet - waiting for EODMS server-side issues to settle) this issue might be able to be closed as fixed 🥳

**Comment by m9brady** [comment]
both `--product-type` and `--radarsat-beam-mnemonic` appear to work now. Give it a try with >=1.1.5:

```bash
eodms -c RS2 -s 20180205 -e 20181231 -pt SGF -rm SCWA -g CG_EODMS_Query.geojson -dr -dfn query_results_v1.1.5
```
