### ISSUE TITLE
Issue with polarization filter -rp

### ISSUE THREAD

**Issue by ECCCBen** [m9brady/eodms-api-client#5]
When querying with the polarization filter I get 0 results but if I remove the filter, I get 932 results which most of them have the desired polarization HH+HV.

`eodms -c RCM -s 2019-08-01 -e 2020-07-31 -g "G:\Shapefile\CG_EODMS_Query.geojson" -rp "HH+HV" -dr`

The geojson polygon file.
https://geojson.io/#map=7/68.094/-111.643

I noticed that in the attribute table the polarization appears as "HH HV". Issue with the "+" in the query input?

**Comment by m9brady** [comment]
Thanks Ben, you're probably right with the space instead of `+`. I was basing it off of the tables in EODMS that have since been updated to remove the `+`: https://www.eodms-sgdot.nrcan-rncan.gc.ca/wes/rapi/collections

Can you attach the geojson file instead of posting the link? Didn't seem to come through with the link...

**Comment by ECCCBen** [comment]
[CG_EODMS_Query.zip](https://github.com/m9brady/eodms-api-client/files/9040100/CG_EODMS_Query.zip)

**Comment by m9brady** [comment]
pushed a new release [v1.2.2](https://github.com/m9brady/eodms-api-client/releases/tag/v1.2.2) that should fix this behaviour with the CLI. It will take a while to get posted to conda-forge so if you don't want to wait, you can do the following:

```python
from eodms_api_client import EodmsAPI
x = EodmsAPI('RCM')
x.query(start='2019-08-01', end='2020-07-31', geometry='./CG_EODMS_Query.geojson', polarization='HH HV')
```

For me this returned 676 results - interestingly there is a result field `Polarization in Product` that reports only `HH` for some images so be sure to drop those before ordering!
